### ISSUE TITLE
(0, _native.useTheme) is not a function using ^7.0.1 on Android emulator

### ISSUE THREAD

**Issue by aibars** [vonovak/react-navigation-header-buttons#130] opened 2021-04-21 21:37 UTC
Hi, 

My app has in one of its component the following navigation options: 

```
export default ({ navigation }: { navigation: NavigationScreenProp<any, any> }) => ({
  headerStyle: {
    ...STYLE.HEADER,
    backgroundColor: navigation.getParam('agencyColor'),
    marginTop: ReportsDashboard.isAndroid ? -24 : 'auto',
    elevation: 0
  },
  headerTitleStyle: {
    fontSize: 16,
    fontWeight: STYLE.FONT.WEIGHTS.MEDIUM
  },
  headerTintColor: STYLE.COLOR.WHITE,
  headerLeft: () => (
    <HeaderButtons left={true}>
      <Item
        title="Menu"
        iconName="menu"
        onPress={() => navigation.dispatch(DrawerActions.toggleDrawer())}
        IconComponent={MaterialIcons}
        iconSize={25}
        color="white"
      />
    </HeaderButtons>
  ),
  headerTitle: () => <Image style={styles.headerLogo} source={navigation.getParam('agencyLogo')} />,
  headerTitleContainerStyle: {
    justifyContent: 'center',
    paddingVertical: 8,
    elevation: 0
  },
  headerBackTitle: ''
});

```
After upgrading Expo to latest version, it upgraded this package to ^7.0.1, but when I run the application on an Android emulator I get the following error:

`(0, _native.useTheme) is not a function. (In '(0, _native.useTheme)()', '(0, _native.useTheme)' is undefined)`

Any help on getting it solved would be much appreciated.

**Comment by vonovak** [comment] 2021-04-21 21:52
hello, thanks for reporting, this is a duplicate of https://github.com/vonovak/react-navigation-header-buttons/issues/122

**Closed by vonovak** 2021-04-21 21:52 UTC
